apiVersion: v1
kind: Service
metadata:
  name: {{ include "dalmatian.fullname" . }}-api
  labels:
    {{- include "dalmatian.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "dalmatian.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
