{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dalmatian.fullname" . }}-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dalmatian.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dalmatian.fullname" . }}-worker-metrics
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dalmatian.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: async-worker
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.monitoring.workerMetricsPort }}
{{- end }}
