{{- if and .Values.valkey.enabled .Values.valkey.persistence.enabled (not .Values.valkey.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dalmatian.fullname" . }}-valkey
  labels:
    {{- include "dalmatian.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.valkey.persistence.storageClassName }}
  storageClassName: {{ .Values.valkey.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.valkey.persistence.size }}
{{- end }}
